### ISSUE TITLE
Not possible to handle exceptions

### ISSUE THREAD

**Issue by hanimayahi** [PayEx/payex-sdk-php#9]
The exceptions thrown in Client::request writes the body in the message string

https://github.com/PayEx/PayEx.Ecommerce.Php/blob/079d59eaef4bacc70ad1acedc09cfefff3379a66/src/PayEx/Api/Client.php#L207

The exception object doesn't have any "body" property that contains the error json from Payex API

The only way to handle exceptions with this implementation would be to search in the message string, which is not optimal.

**Comment by asbjornu** [comment]
Since PayEx' API returns [`application/problem+json`](https://developer.payex.com/xwiki/wiki/developer/view/Main/ecommerce/technical-reference/#HProblems), exceptions thrown should only use the `title` property as the exception title and add the rest of the JSON properties as properties on the exception so they can be explored individually.

**Comment by aait** [comment]
@hanimayahi Please upgrade that library to latest version.
